version: 2

models: []
sources:
  - name: default
    database: dev
    schema: dbt_shadow_prod

    freshness:
      warn_after: {count: 999999, period: day}

    tables:
      - name: test_events
        identifier: test_events
        loaded_at_field: timestamp
